version: '3.8'

services:
  spark-jupyter:
    build: .
    container_name: spark-jupyter-container
    ports:
      - "8888:8888"  # Jupyter Lab
      - "4040:4040"  # Spark Application UI
      - "8080:8080"  # Spark Master UI
      - "7077:7077"  # Spark Master Port
    volumes:
      - ./notebooks:/workspace/notebooks
      - ./data:/workspace/data
      - ./src:/workspace/src
      - .:/workspace/project
      - ./src:/workspace/src  # Mount your local code directory
    environment:
      - JUPYTER_ENABLE_LAB=yes
    restart: unless-stopped
    networks:
      - spark-network

  minio:
    image: quay.io/minio/minio
    container_name: minio-container
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - C:/Users/zzac810/Documents/minio/data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: ["server", "/data", "--console-address", ":9001"]
    restart: unless-stopped
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge